print ("Hola!")
print ("esta es semana 4")
print ("hoy vamos a aprender de python")
print ("python es un lenguaje de programación de alto nivel")
print ("esto lo hace mas sencillo de aprender aunque mas lento a la hora de correrlo")
print ("python se usa para todo tipo de apps como web, videojuegos, analisis de datys y AI")
print ("en este ejercicion mostrare el resultado de operaciones basicas con python")
print ("el resultado de 3 x 42 es:")
print (3*42)
print ("el resultado de 125 dividido entre 5 es:")
print (125/5)
print ("el resultado de 89 + 98 es:")
print (89+98)
